language: node_js

node_js:
 - 4
 - 6

os:
 - linux
 - osx

osx_image: xcode8.1

env:
  matrix:
    - TEST=normal
    - TEST=integration

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
            export CXX=g++-4.8;
            sleep 8;
      fi
    - if [[ "$TEST" == "integration" ]]; then
            export PATH="$HOME/.meteor:$PATH";
            if [[ $(npm -v) != 4* ]]; then npm i -g npm@4; fi;

            if hash meteor 2>/dev/null;
            then
                meteor --version;
            else
                curl https://install.meteor.com/?release=1.4.2.3 | /bin/sh;
            fi;
      fi


script:
    - if [[ "$TEST" == "normal" ]]; then
        npm test;
      fi
    - if [[ "$TEST" == "integration" ]]; then
            npm run prepare-integration-tests;
            npm run test-integration;
      fi

after_success:
  - if [[ "$TEST" == "normal" ]]; then
      npm run coverage;
      npm run report-coverage;
    fi

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/.npm
    - $HOME/.meteor
    - tests/.__tmp_int

notifications:
  email:
    on_success: never
    on_failure: change
