build: off

os: unstable

skip_tags: true

environment:
  matrix:
    - nodejs_version: "8"
      test: "normal"
      platform: x64
    - nodejs_version: "8"
      test: "integration"
      platform: x64
    - nodejs_version: "10"
      test: "integration"
      platform: x64
    - nodejs_version: "10"
      test: "normal"
      platform: x64

cache:
  - node_modules -> appveyor.yml
  - '%APPDATA%\npm\node_modules -> appveyor.yml'
  - '%APPDATA%\npm-cache -> appveyor.yml'
  - '%USERPROFILE%\.electron -> appveyor.yml'
  - '%LOCALAPPDATA%\Yarn -> appveyor.yml'
  - '%LOCALAPPDATA%\.meteor -> appveyor.yml'
#   - tests/.__tmp_int -> appveyor.yml

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@6
  - npm prune
  - npm install
  - ps: >-
      if ($env:test -eq "integration") {
        if ((Get-Command "meteor" -ErrorAction SilentlyContinue) -eq $null) {
          choco install meteor --params "'/RELEASE:1.5.4.1'"
        }
      }
  - ps: refreshenv
  - cmd: refreshenv

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - if %test%==integration meteor --version
  - if not %test%==integration npm test
  - if %test%==integration npm run prepare-integration-tests
  - if %test%==integration npm run test-integration

#
# cache clear

